[project]
name = "quickstart-app-1-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "docusign-esign>=5.4.0",
    "fastapi>=0.125.0",
    "uvicorn>=0.38.0",
]
